Feature: Refactor American/British Translator Project Boilerplate for a Backend Focus to Improve Testability
freeCodeCamp/boilerplate-project-american-british-english-translator pull request #6
Opened 2020-10-05 19:24 UTC by SaintPeter

As discussed here:
https://github.com/freeCodeCamp/freeCodeCamp/issues/39692

@nhcarrigan and I refactored this project to have a more backend focus to improve testability by the fCC test infrastructure.

Key Changes:
* Removed all front-end related User Stories 
* Rewrote the front-end to provide minimal features, treating it as a basic API endpoint test
* Moved all logic to the back-end.
* Added unit tests to cover highlighting
* Added functional tests to cover the new API endpoint

NOTE: This change should not be merged until the (as yet uncreated) `/learn` PR has been completed.

2020-10-12 16:02 UTC, SaintPeter commented
Removed user stories as described in https://github.com/freeCodeCamp/freeCodeCamp/issues/39721

2020-10-14 14:57 UTC, moT01 approved these changes
As far as I can tell, I think this boilerplate LGTM 🎉

I made some suggestions on the other two PR's.

2020-11-05 23:01 UTC, RandellDawson requested changes
@SaintPeter I have a question and a suggestion.  If you make any of these changes, will you have to change anything else to avoid test failures?

2020-11-05 23:01 UTC, RandellDawson commented on tests/1_unit-tests.js
> +      const output = 'Lunch is at 12.15 today.';
Shouldn't this be either:
```js
    test('Tea time is usually around 4 or 4.30. --> Tea time is usually around 4:00 or 4:30.', done => {
      const input = 'Tea time is usually around 4 or 4.30 today.';
      const output = 'Tea time is usually around 4:00 or 4:30 today.';
```
OR
```js
    test('Tea time is usually around 4 or 4.30. --> Tea time is usually around 4or 4:30.', done => {
      const input = 'Tea time is usually around 4 or 4.30 today.';
      const output = 'Tea time is usually around 4 or 4:30 today.';
```

2020-11-05 23:01 UTC, RandellDawson commented on tests/1_unit-tests.js
> +        const output = '<span class="highlight">Mangoes</span> are my favourite fruit.';
Shouldn't this be:
```suggestion
        const output = 'Mangoes are my <span class="highlight">favourite</span> fruit.';
```

2020-11-05 23:32 UTC, nhcarrigan commented on tests/1_unit-tests.js
> +      const output = 'Lunch is at 12.15 today.';
Yes.

2020-11-05 23:32 UTC, nhcarrigan commented on tests/1_unit-tests.js
> +        const output = '<span class="highlight">Mangoes</span> are my favourite fruit.';
Also yes.

2020-11-05 23:32 UTC, nhcarrigan commented
@SaintPeter did we lose a commit here? I feel like these are things we already fixed? (Or am I just losing it?)

2020-11-06 00:48 UTC, SaintPeter commented
I have fixed these issues here and in the demo project.

2020-11-06 19:59 UTC, RandellDawson requested changes
@SaintPeter I have one small question/suggestion.  Everything else seems fine.  I tested it out but simply copying/pasting the relevant code from the example project you created and then tested against the corresponding `/learn` PR and everything passes.

Great job!

2020-11-06 19:59 UTC, RandellDawson commented on routes/api.js
> +  let translator = new Translator();
I notice this line here, but in the PR you created for the example project, you did not actually incorporate this line as you never instantiated `Translator`.  I suppose I am fine leaving it, but I would prefer using `const`.
```suggestion
  const translator = new Translator();
```

2020-11-06 23:21 UTC, RandellDawson approved these changes

2020-11-06 23:25 UTC, RandellDawson commented
OK, this PR looks good now.

@moT01 I have approved https://github.com/freeCodeCamp/freeCodeCamp/pull/39822 and https://github.com/freeCodeCamp/demo-projects/pull/23, so if you approve, we can merge this as soon as the `/learn` PR hits production.

2020-11-07 19:29 UTC, moT01 approved these changes
👍 @SaintPeter @nhcarrigan 🚀 The main PR is now on production so this can get merged 😄

2020-11-07 19:30 UTC, merged